// Command refforge emits a Kotlin source file of fixed-input reference vectors
// for the app-side transport crypto. The inputs (static keys, ephemerals, PSK)
// are constant so the output is reproducible; the Kotlin JVM tests assert
// byte-for-byte equality against it.
package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"

	"github.com/flynn/noise"

	"github.com/heavycaffeiner/remotly/daemon/internal/protocol"
)

func seed(b byte) []byte {
	k := make([]byte, 32)
	for i := range k {
		k[i] = b + byte(i)
	}
	return k
}

func kp(b byte) noise.DHKey {
	k, _ := noise.DH25519.GenerateKeypair(bytes.NewReader(seed(b)))
	return k
}

type hand struct {
	msg1, msg2, msg3 string
	c1, c2, peer     string
}

func runIK() hand {
	suite := noise.NewCipherSuite(noise.DH25519, noise.CipherChaChaPoly, noise.HashBLAKE2b)
	si, sr := kp(0x11), kp(0x22)
	pro := []byte(protocol.Prologue)
	ci := noise.Config{Pattern: noise.HandshakeIK, Initiator: true, CipherSuite: suite, StaticKeypair: si, PeerStatic: sr.Public, Prologue: pro, Random: bytes.NewReader(seed(0xE1))}
	cr := noise.Config{Pattern: noise.HandshakeIK, CipherSuite: suite, StaticKeypair: sr, Prologue: pro, Random: bytes.NewReader(seed(0xE2))}
	hsI, _ := noise.NewHandshakeState(ci)
	hsR, _ := noise.NewHandshakeState(cr)
	m1, _, _, _ := hsI.WriteMessage(nil, nil)
	_, _, _, err := hsR.ReadMessage(nil, m1)
	check(err)
	m2, _, _, err := hsR.WriteMessage(nil, nil)
	check(err)
	_, cs1, cs2, err := hsI.ReadMessage(nil, m2)
	check(err)
	c1 := cs1.UnsafeKey()
	c2 := cs2.UnsafeKey()
	return hand{hex.EncodeToString(m1), hex.EncodeToString(m2), "", hex.EncodeToString(c1[:]), hex.EncodeToString(c2[:]), hex.EncodeToString(sr.Public)}
}

func runXX() hand {
	suite := noise.NewCipherSuite(noise.DH25519, noise.CipherChaChaPoly, noise.HashBLAKE2b)
	si, sr := kp(0x33), kp(0x44)
	psk := seed(0xAA)
	pro := []byte(protocol.Prologue)
	ci := noise.Config{Pattern: noise.HandshakeXX, Initiator: true, CipherSuite: suite, StaticKeypair: si, PresharedKey: psk, PresharedKeyPlacement: 0, Prologue: pro, Random: bytes.NewReader(seed(0xE3))}
	cr := noise.Config{Pattern: noise.HandshakeXX, CipherSuite: suite, StaticKeypair: sr, PresharedKey: psk, PresharedKeyPlacement: 0, Prologue: pro, Random: bytes.NewReader(seed(0xE4))}
	hsI, _ := noise.NewHandshakeState(ci)
	hsR, _ := noise.NewHandshakeState(cr)
	m1, _, _, _ := hsI.WriteMessage(nil, nil)
	_, _, _, err := hsR.ReadMessage(nil, m1)
	check(err)
	m2, _, _, _ := hsR.WriteMessage(nil, nil)
	_, _, _, err = hsI.ReadMessage(nil, m2)
	check(err)
	m3, cs1, cs2, err := hsI.WriteMessage(nil, nil)
	check(err)
	_, _, _, err = hsR.ReadMessage(nil, m3)
	check(err)
	c1 := cs1.UnsafeKey()
	c2 := cs2.UnsafeKey()
	return hand{hex.EncodeToString(m1), hex.EncodeToString(m2), hex.EncodeToString(m3), hex.EncodeToString(c1[:]), hex.EncodeToString(c2[:]), hex.EncodeToString(sr.Public)}
}

type frame struct {
	chType, chID int
	wire         string
}

func sealFrames(sendKeyHex string, specs [][3]uint64) []frame {
	key, _ := hex.DecodeString(sendKeyHex)
	var k [32]byte
	copy(k[:], key)
	cipher := protocol.NewChaCha(k, k)
	out := []frame{}
	for _, s := range specs {
		payload := make([]byte, s[2])
		for i := range payload {
			payload[i] = byte(i)
		}
		wire, err := cipher.SealFrame(byte(s[0]), uint32(s[1]), payload)
		check(err)
		out = append(out, frame{int(s[0]), int(s[1]), hex.EncodeToString(wire)})
	}
	return out
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "refforge:", err)
		os.Exit(1)
	}
}

func q(s string) string { return `"` + s + `"` }

func main() {
	ik := runIK()
	xx := runXX()
	specs := [][3]uint64{
		{0, 0, 0},
		{0, 0, 5},
		{1, 7, 1000},
		{1, 0xFFFFFFFF, 3},
	}
	dirA := sealFrames(ik.c1, specs)
	dirB := sealFrames(ik.c2, specs)
	vin := []uint64{0, 1, 127, 128, 300, 0xFFFFFFFF, 5}

	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("// Generated by daemon/tools/refforge. Do not edit by hand.\n")
	w("// Fixed-input reference vectors for the Noise handshake and frame cipher.\n")
	w("package com.remotly.app.transport\n\n")
	w("object TransportVectors {\n")
	w("    val prologue: ByteArray = \"%s\".encodeToByteArray()\n", protocol.Prologue)
	w("    val version = %d\n", protocol.Version)
	w("    // IK handshake: initiator writes msg1, reads msg2.\n")
	w("    val ik = VecHandshake(%s, %s, %s, %s, %s, %s)\n", q(ik.msg1), q(ik.msg2), q(""), q(ik.c1), q(ik.c2), q(ik.peer))
	w("    // XXpsk0 handshake: initiator writes msg1, reads msg2, writes msg3.\n")
	w("    val xx = VecHandshake(%s, %s, %s, %s, %s, %s)\n", q(xx.msg1), q(xx.msg2), q(xx.msg3), q(xx.c1), q(xx.c2), q(xx.peer))
	w("    // Direction A frames are sealed with the IK send key (c1), as the app\n")
	w("    // would seal its own outgoing frames.\n")
	w("    val framesA = listOf(\n")
	for _, f := range dirA {
		w("        VecFrame(%d, %dL, %s),\n", f.chType, f.chID, q(f.wire))
	}
	w("    )\n")
	w("    // Direction B frames are sealed with the IK recv key (c2), as the\n")
	w("    // daemon would seal frames it sends to the app.\n")
	w("    val framesB = listOf(\n")
	for _, f := range dirB {
		w("        VecFrame(%d, %dL, %s),\n", f.chType, f.chID, q(f.wire))
	}
	w("    )\n")
	w("    val varintValues = longArrayOf(\n")
	for _, v := range vin {
		w("        %dL,\n", v)
	}
	w("    )\n")
	w("    val varintHex = listOf(\n")
	for _, v := range vin {
		w("        %s,\n", q(hex.EncodeToString(protocol.AppendVarint(nil, v))))
	}
	w("    )\n")
	w("    // Fixed key material (X25519 seeds) used to build the vectors.\n")
	w("    val ikInitStaticSeed = %s\n", q(hex.EncodeToString(seed(0x11))))
	w("    val ikRespStaticSeed = %s\n", q(hex.EncodeToString(seed(0x22))))
	w("    val xxInitStaticSeed = %s\n", q(hex.EncodeToString(seed(0x33))))
	w("    val xxRespStaticSeed = %s\n", q(hex.EncodeToString(seed(0x44))))
	w("    val xxPsk = %s\n", q(hex.EncodeToString(seed(0xAA))))
	w("    val ephIkJ1 = %s\n", q(hex.EncodeToString(seed(0xE1))))
	w("    val ephIkJ2 = %s\n", q(hex.EncodeToString(seed(0xE2))))
	w("    val ephXxJ1 = %s\n", q(hex.EncodeToString(seed(0xE3))))
	w("    val ephXxJ2 = %s\n", q(hex.EncodeToString(seed(0xE4))))
	w("}\n\n")
	w("class VecHandshake(val msg1: String, val msg2: String, val msg3: String, val c1: String, val c2: String, val peer: String)\n\n")
	w("class VecFrame(val chType: Int, val chId: Long, val wire: String)\n")

	os.Stdout.Write(b.Bytes())
}
